from source import db
from source.main.model.AddSuKien import AddSuKien
from source.main.model.BlockUser import BlockUser
from source.main.model.CategoriesVideo import CategoriesVideo
from source.main.model.Comment import Comment
from source.main.model.DeviceTokenIos import DeviceTokenIos
from source.main.model.GmailFrom import GmailFrom
from source.main.model.ListAlbum import ListAlbum
from source.main.model.ListImageAlone import ListImageAlone
from source.main.model.ListImageBaby import ListImageBaby
from source.main.model.ListImageBikini import ListImageBikini
from source.main.model.ListImageFancyAI import ListImageFancyAI
from source.main.model.ListImageMotherBaby import ListImageMotherBaby
from source.main.model.ListImagePreg import ListImagePreg
from source.main.model.ListImageSanta import ListImageSanta
from source.main.model.ListImageWedding import ListImageWedding
from source.main.model.ListVideo import ListVideo
from source.main.model.ListVideoAnime import ListVideoAnime
from source.main.model.ListVideoBaby import ListVideoBaby
from source.main.model.ListVideoBabyfunny import ListVideoBabyFunny
from source.main.model.ListVideoBabyFuture import ListVideoBabyFuture
from source.main.model.ListVideoCatwalk import ListVideoCatwalk
from source.main.model.ListVideoHallowen import ListVideoHallowen
from source.main.model.ListVideoMebau import ListVideoMebau
from source.main.model.ListVideoModel import ListVideoModel
from source.main.model.ListVideoSanta import ListVideoSanta
from source.main.model.ListVideoSantaNew import ListVideoSantaNew
from source.main.model.ListVideoWedding import ListVideoWedding
from source.main.model.Messages import Messages
from source.main.model.MotherBaby import MotherBaby
from source.main.model.ReportComment import ReportComment
from source.main.model.ReportSuKien import ReportSuKien
from source.main.model.SavedImage import SavedImage
from source.main.model.SavedNotifi import SavedNotifi
from source.main.model.SavedSKVideoImageGrowup import SavedSKVideoImageGrowup
from source.main.model.SavedSKVideoImageMeBau import SavedSKVideoImageMeBau
from source.main.model.SavedSKVideoImageWedding import SavedSKVideoImageWedding
from source.main.model.SavedSKVideoSwapImage import SavedSKVideoSwapImage
from source.main.model.SavedSuKien import SavedSuKien
from source.main.model.SavedSuKien2Img import SavedSuKien2Img
from source.main.model.SavedSuKienAlone import SavedSuKienAlone
from source.main.model.SavedSuKienSwapBaby import SavedSuKienSwapBaby
from source.main.model.SavedSuKienVideo import SavedSuKienVideo
from source.main.model.Users import Users
from source.main.model.VideoWedding import VideoWedding
from source.main.model.WeddingDetail import WeddingDetail

if __name__ == "__main__":
    db.create_all()
